apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mongoexpress-deployment
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name : mongoc
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongoexpress-map
              key: mongoserverurl
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongosecret
              key: username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongosecret
              key: password

---
apiVersion: v1
kind: Service
metadata:
  name: express
spec:
  selector:
    app: mongo-express
  type: LoadBalancer
  ports:
   - protocol: 'TCP'
     port: 8081
     targetPort: 8081
     nodePort: 30000